# Generated by Django 4.0.5 on 2023-12-09 22:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('name', models.CharField(default='Канал', max_length=64)),
                ('state', models.BooleanField(default=False)),
                ('season', models.IntegerField(default=100)),
                ('temp_min', models.IntegerField(default=8)),
                ('temp_max', models.IntegerField(default=32)),
                ('meandr_on', models.IntegerField(default=60)),
                ('meaoff_cmin', models.IntegerField(default=0)),
                ('meaoff_cmax', models.IntegerField(default=0)),
                ('press_on', models.FloatField(default=0)),
                ('press_off', models.FloatField(default=0)),
                ('volume_min', models.FloatField(default=0.0)),
                ('volume_max', models.FloatField(default=0.0)),
                ('lowlevel', models.BooleanField(default=False)),
                ('rainsens', models.BooleanField(default=True)),
                ('tempsens', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=2)),
                ('mqtt_host', models.CharField(default='', max_length=30)),
                ('mqtt_port', models.CharField(default='', max_length=30)),
                ('mqtt_user', models.CharField(default='', max_length=30)),
                ('mqtt_password', models.CharField(default='', max_length=30)),
                ('mqtt_prefix', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('day', models.IntegerField(default=0)),
                ('week', models.BooleanField(default=False)),
                ('nearest_chn', models.IntegerField(default=1)),
                ('nearest_time', models.TimeField(default=datetime.time(0, 0))),
                ('t1', models.FloatField(default=0)),
                ('t1_active', models.BooleanField(default=False)),
                ('t2', models.FloatField(default=0)),
                ('t2_active', models.BooleanField(default=False)),
                ('t_amount', models.IntegerField(default=1)),
                ('rain', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('ip', models.CharField(default='0.0.0.0', max_length=16)),
                ('esp_v', models.CharField(default='0.0.0', max_length=12)),
                ('esp_connected', models.BooleanField(default=False)),
                ('esp_ap', models.BooleanField(default=False)),
                ('esp_net', models.BooleanField(default=False)),
                ('esp_mqtt', models.BooleanField(default=False)),
                ('esp_errors', models.BooleanField(default=False)),
                ('pressure', models.FloatField(default=0)),
                ('stream', models.FloatField(default=0)),
                ('remote_block0', models.IntegerField(default=0)),
                ('remote_block1', models.IntegerField(default=0)),
                ('remote_block2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserControllerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mqtt_password', models.CharField(default='', max_length=32)),
                ('verbous_name', models.CharField(default='Контроллер', max_length=32)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.controller')),
                ('user_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userextension')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(default='', max_length=7)),
                ('weeks', models.SmallIntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('t_min', models.IntegerField(default=0)),
                ('t_max', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.channel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now=True)),
                ('avr_time', models.TimeField(blank=True, default=None, null=True)),
                ('temp0', models.IntegerField(blank=True, default=None, null=True)),
                ('temp1', models.IntegerField(blank=True, default=None, null=True)),
                ('pressure', models.IntegerField(blank=True, default=None, null=True)),
                ('wspd', models.IntegerField(blank=True, default=None, null=True)),
                ('rain', models.BooleanField(blank=True, default=None, null=True)),
                ('pause', models.BooleanField(blank=True, default=None, null=True)),
                ('alarm', models.BooleanField(blank=True, default=None, null=True)),
                ('rssi', models.IntegerField(blank=True, default=None, null=True)),
                ('channels_state', models.IntegerField(blank=True, default=None, null=True)),
                ('cykl', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.controller')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.controller'),
        ),
        migrations.AddConstraint(
            model_name='usercontrollerpreferences',
            constraint=models.UniqueConstraint(fields=('user_extension', 'controller'), name='unique_user_controller_combination'),
        ),
    ]
