# Generated by Django 4.0.5 on 2022-10-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_cmax_channel_temp_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='number',
        ),
        migrations.AlterField(
            model_name='channel',
            name='temp_max',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='channel',
            name='temp_min',
            field=models.IntegerField(default=8),
        ),
    ]
