# Generated by Django 4.0.5 on 2022-11-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_program_number_alter_channel_temp_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
