# Generated by Django 4.0.5 on 2022-11-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_controller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='status',
            field=models.IntegerField(default=False),
        ),
    ]
