# Generated by Django 4.0.5 on 2022-11-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_controller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='t1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controller',
            name='t2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controller',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
