# Generated by Django 4.0.5 on 2022-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_controller_t1_active_controller_t2_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='press_off',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='press_on',
            field=models.FloatField(default=0),
        ),
    ]
