# Generated by Django 4.0.5 on 2022-11-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_channel_press_off_alter_channel_press_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='saved_controllers',
        ),
        migrations.CreateModel(
            name='UserControllerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbous_name', models.CharField(default='Контроллер', max_length=32)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.controller')),
                ('user_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userextension')),
            ],
        ),
    ]
