# Generated by Django 4.0.5 on 2022-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_userextension_saved_controllers_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercontrollerpreferences',
            constraint=models.UniqueConstraint(fields=('user_extension', 'controller'), name='unique_user_controller_combination'),
        ),
    ]
