# Generated by Django 4.0.5 on 2022-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_usercontrollerpreferences_unique_user_controller_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontrollerpreferences',
            name='mqtt_password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
