# Generated by Django 4.0.5 on 2022-11-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_usercontrollerpreferences_mqtt_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='name',
        ),
    ]
