# Generated by Django 4.0.5 on 2022-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_controller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='remote_block0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controller',
            name='remote_block1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controller',
            name='remote_block2',
            field=models.IntegerField(default=0),
        ),
    ]
